import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import styles from "./page.module.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className={styles.main}>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
